version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: postgres_v13
    ports:
      - "65432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    restart: always
  pgadmin:
    image: dpage/pgadmin4:6.11
    container_name: pgadmin4_v6
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=example@example.com
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - D:\sqlalchemy-trial\volume\pgadmin4:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: always