version: "3.8"

services:
  alembic:
    build:
      context: .
      dockerfile: docker/alembic/Dockerfile
    container_name: alembic
    environment:
      - PYTHONPATH=${PYTHONPATH}:/root/src
    volumes:
      - ./:/root
    tty: true
  postgres:
    image: postgres:13
    container_name: postgres_v13
    ports:
      - "65432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    restart: always
  pgadmin:
    image: dpage/pgadmin4:6.11
    container_name: pgadmin4_v6
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=example@example.com
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - .volumes/pgadmin4:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: always